# Generated by Django 5.2.7 on 2025-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='none', max_length=255)),
                ('year', models.IntegerField(default='none', max_length=255)),
                ('color', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(default='none', max_length=255)),
                ('cocoa_percentage', models.IntegerField(default='none', max_length=255)),
                ('price', models.IntegerField(default='none', max_length=255)),
                ('sugar_percentage', models.IntegerField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('price', models.IntegerField(default='none', max_length=255)),
                ('sector', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('age', models.IntegerField(default='none', max_length=255)),
                ('major', models.CharField(default='none', max_length=255)),
                ('grades', models.IntegerField(default='none', max_length=255)),
            ],
        ),
    ]
