# Generated by Django 5.2.7 on 2025-11-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('sector', models.CharField(default='none', max_length=255)),
                ('location', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
