# Generated by Django 5.2.7 on 2025-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_companys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('subject', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
