# Generated by Django 5.2.7 on 2025-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cold_drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('brand', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(default='none', max_length=255)),
                ('flavor', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
