# Generated by Django 5.2.7 on 2025-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_cold_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cold_drinks',
            name='firstname',
        ),
        migrations.AddField(
            model_name='cold_drinks',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
