# Generated by Django 5.2.7 on 2025-11-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_remove_cold_drinks_firstname_cold_drinks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cold_drinks',
            name='type',
        ),
    ]
