# Generated by Django 5.2.7 on 2025-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_remove_cold_drinks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='surname',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
